version: '2'

services:
  # api server
  api:
    build: .
    ports:
      - 5000:5000
    links:
      - mysql
      - redis
    volumes:
      - .:/go/src/github.com/CANARIA/canaria-api
    command: bash -c 'cd /go/src/github.com/CANARIA/canaria-api/ && go run server.go'
    environment:
      - DB_HOST=mysql
    container_name: canaria-api

  # mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=canaria
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    container_name: canaria-db

  # redis
  redis:
    image: redis:3.0.7-alpine
    ports:
      - 6379:6379
    container_name: canaria-cache

  # redis viewer
  redis-commander:
    image: diyan/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - 8081:8081
    container_name: canaria-cache-viewer

volumes:
  db-data:
    driver: local
