version: '2'

services:
  api:
    build: .
    ports:
      - 5000:5000
    links:
      - mysql
      - redis
    volumes:
      - .:/go/src/github.com/CANARIA/canaria-api
    command: bash -c 'cd /go/src/github.com/CANARIA/canaria-api/ && go run server.go'
    environment:
      - DB_HOST=mysql
    container_name: canaria-api

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=canaria
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    container_name: canaria-db

  redis:
    image: redis:3.0.7
    container_name: canaria-cache

volumes:
  db-data:
    driver: local
